# Generated by Django 3.1.7 on 2021-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'HUMIDITY',
            },
        ),
        migrations.CreateModel(
            name='Lfw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'LEAF_WETNESS',
            },
        ),
        migrations.CreateModel(
            name='Prs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'PRESSURE',
            },
        ),
        migrations.CreateModel(
            name='Rnf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'RAINFALL',
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('sensor_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Swp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'SWP',
            },
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'TEMPERATURE',
            },
        ),
        migrations.CreateModel(
            name='Wnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'WIND_DIRECTION',
            },
        ),
        migrations.CreateModel(
            name='Wng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'WIND_GUST',
            },
        ),
        migrations.CreateModel(
            name='Wns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.FloatField(null=True)),
                ('signal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'WIND_SPEED',
            },
        ),
    ]
